demo_auth_rest_homepage:
    pattern:  /
    defaults: { _controller: DemoAuthRestBundle:Default:index }

login:
    pattern:   /login
    defaults:  { _controller: DemoAuthRestBundle:Default:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

user:
    type: rest
    resource: Demo\AuthRestBundle\Controller\UserController
    prefix: api