parameters:
#    demo_auth_rest.example.class: Demo\AuthRestBundle\Example

services:
#    demo_auth_rest.example:
#        class: %demo_auth_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
